### ISSUE TITLE
CCX: asynchronous grade download

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#108]
As a CCX coach I need to download student grades and with CCXs with many students this download can timeout. I need a way to request a download and pick it up later. 

This will require some more research after #88 is addressed. We would like to use the same queuing infrastructure that's used in the data download tab of the instructor dashboard, but we would like to move it into the coach's dashboard. I'm not sure if the instructor dashboard is sufficiently modular for this approach.

**Comment by pdpinch** [comment]
Blocked until the permissions issues in #88 are resolved

**Comment by amir-qayyum-khan** [comment]
@pdpinch 

- Now we have max students per ccx = 200. Do we need this task.

- User can download grade book from his ccx. Their is one grade book and one ccx. Why he want to request for download instead of just download?

-  If he request to download grade book. the what will happen ? when next time he opens his dashboard app will automatically download (release) his grade book csv file? what is the point when he want to get his grade book file.

- Is this for a guy who is coach on multiple ccx and we want one queue for all his ccx so that he can get one grade book from one ccx at the time?

- I think he needs a fast download manager who can download file in parts. Do i need to create a downloader for grade book? who can effectively download large files?

**Comment by pdpinch** [comment]
Performance of the gradebook scales both with students and with the number of problems. Even at 90 students, the Davidson courses (and MIT physics courses) are too large and timeout before the current download mechanism is successful. 

edX has addressed this already in the "data Download" section of the instructor dashboard. The instructor requests a grade report, the request goes into a queue. The instructor can view the status of the request in the queue, and download the file from S3 when it's ready. 

We can't give Coaches direct access to "Data Download" however, and it wouldn't be a good UX. What we want to do is expose (or maybe copy) that functionality from the instructor dashboard to the coach dashboard. 

As I said above, this story starts with research of the queuing in the instructor dashboard.

**Comment by amir-qayyum-khan** [comment]
Fixed via https://github.com/mitocw/edx-platform/pull/157

**Comment by pdpinch** [comment]
This can be closed when edx#11092 is merged.

**Comment by pdpinch** [comment]
This issue is moot, now that coaches have access to the instructor dashboard.
