### ISSUE TITLE
look at edx-notes-api backend 

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#112]
https://github.com/edx/edx-notes-api

- [ ] Can it be reused to support other media types, in particular video?
- [ ] Can it be extended to manage shared annotations?
      Share with class, share with staff

**Comment by ShawnMilo** [comment]
@jamiefolsom: Regarding the first question, does the standard annotation model allow for the `ranges` to accept data for different media types? I believe the answer to the first checkbox is "yes" by default, but I'd like the benefit of your experience.

**Comment by ShawnMilo** [comment]
For the second question, this is possible with schema and API changes.

There's also the [question](https://docs.google.com/document/d/1nh2fhqlBAz_hNgW3tn_ewBU1Oi70GqB3aYeiom_VW00/edit) here about allowing an instructor to limit who can view things by date period.

**Comment by jamiefolsom** [comment]
Hi @ShawnMilo,

Typically, `ranges` is an array of objects, each containing four fields: `start`, `end`, `start offset`, `end offset`, but in this case, having this morning discussed this api with Justin, it appears that ranges is a simple JSON field, and therefore may be reusable. Frankly, I don't know why we wouldn't keep ranges focused on text anchors, and add new fields for video anchors (with `in point`, `out point` timestamps), for image anchors or shapes (containing `start x`, `start y`, `width` and `height`, for boxes, or `center x`, `center y`, and `radius` for circles), etc. 

On the second question, we implemented sharing by adding a groups field and a subgroups field, each of which was just an array of strings, each string being a group with whom the annotation was shared., which worked well.

Thoughts?

**Comment by ShawnMilo** [comment]
@jamiefolsom: Thank you for the explanation. I think this means we can answer both of @pdpinch's questions with: "Yes, pending some API and schema changes which shouldn't be very disruptive." Do you agree with this characterization?

**Comment by jamiefolsom** [comment]
Yes, I agree. The storage of annotations with anchors for any media type is not very difficult. The change to the data store API app I wrote to support images was a minor one, as you can see here: https://github.com/hyperstudio/MIT-Annotation-Data-Store/pull/4

Building a UI that allows viewing, adding and editing annotations on a new media type is more work, as each media type will require largely separate UI controls (for video, image, text, etc).

**Comment by ShawnMilo** [comment]
Thanks, @jamiefolsom.

@pdpinch: The results of this research mostly show that `edx-notes-api` is, more or less, an implementation of the annotator storage API. Not much is fancy.

Some items of interest:

- Unlike a standard annotator storage backend, this API does not accept or store URIs. Instead, it uses `course_id` and `usage_id`, the latter being the nickname for "xblock ID"
- The backend stores data in both ElasticSearch and the relational database defined in the Django settings, and will return from results from one or the other depending on the query
- Highlighting of results is supported, but only when ElasticSearch is the backend
- The API prefers the ORM backend over ElasticSearch for all queries when search text is not provided.
- `course_id` is the only required field for performing a query
- `PUT` requests (updates) to an annotation only update the `text` and `tags`, all other fields are ignored
- If the annotation ID is provided in the querystring, even for non-`GET` requests, it will be used, even if a different annotation ID is provided in the `POST` or `PUT` data
- Attempting to delete an ID that doesn't exist results in an error, instead of just a `204 - No data`
- Annotations may be an empty string (`""`)
- Results are returned in last-modified order if provided by the ORM, and by ElasticSearch weight if ElasticSearch

**Comment by pdpinch** [comment]
Thanks. Very helpful.
