### ISSUE TITLE
OAuth template

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#176]
maybe just an HTML file?

**Comment by justinabrahms** [comment]
Unlikely to be just an HTML file.

edx/django-oauth2-provider uses django templates. edx uses mako templates via an app in edx/edx-platform called `edxmako`

We can't depend on edx/edx-platform from edx/django-oauth2-provider. We could possibly pull django-oauth2-provider into edx-platform, but that seems like they wouldn't like that.

Another option would be to find a place in edx-platform to subclass all of the relevant class-based views in django-oauth2-provider. From there, we could override those views to speak mako instead of django templates by overriding `django.views.generic.TemplateView`'s `response_class` field to something that adheres to this interface: https://github.com/django/django/blob/master/django/template/response.py#L141


Context: https://openedx.slack.com/archives/general/p1453399862002211

**Comment by pdpinch** [comment]
I'm confused. I thought Clinton said in the slack conversation that django templates would be OK?

> Context: https://openedx.slack.com/archives/general/p1453399862002211 <https://openedx.slack.com/archives/general/p1453399862002211>

**Comment by justinabrahms** [comment]
He did. This comment was posted before he responded.

**Comment by justinabrahms** [comment]
![oauth-2-confirmation](https://cloud.githubusercontent.com/assets/3853/12655382/b0ec042c-c5c6-11e5-8828-3a30f2408b29.png)

Thoughts, @jamiefolsom ? 

I still need to get the button in the top right to work, but this seems reasonable to me?
