### ISSUE TITLE
Access CCX dashboard through CCX (in addition to accessing it through master course)

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#33]
via Chris Chudziki:

> Accessing CCX Dashboard
> Currently coaches can only access the CCX Dashboard through the base course. This seems to be a strange setup: to manage my CCX, I need to enter a different course.

> Suggestion: Allow coaches to enter CCX Dashboard through either base course or custom course and make changes in picture below.

<img width="577" alt="screen shot 2015-10-27 at 10 31 20 am" src="https://cloud.githubusercontent.com/assets/430126/10761036/f42efa84-7c95-11e5-9f22-923be1523470.png">

**Comment by pdpinch** [comment]
When we started using CCX keys, the coach dashboard remained attached to the course key instead of going with the CCX key. Given the function, it would make sense for it to be with the CCX, but some kind of way-finding to move folks from the course to the CCX would be nice. 

Also, Ike and Dan had expressed concern about having to message all their coaches with unique URLs to find their CCXs. 

Maybe we need a dashboard on the master course that helps the coach find her CCXs and a dashboard on the CCX for managing the specific CCX's settings.

**Comment by justinabrahms** [comment]
Trying to wrap my head around this. It sounds like the problem is that having to go into the original course to get to the CCX tab is undesireable. Instead, they want a separate listing on the dashboard. Is that right?

Should that be listed on the main course? Or shown as a separate course? Examples below of what I think we're talking about.


### Current
![screenshot from 2015-10-23 11 17 56](https://cloud.githubusercontent.com/assets/3853/10701436/5ea15b30-7978-11e5-863a-545f10c3c6b2.png)

### Listed on main course
![screenshot from 2015-10-23 11 20 25](https://cloud.githubusercontent.com/assets/3853/10701440/62849a32-7978-11e5-9b1e-73fa679062b1.png)

### Listed as separate course
![screenshot from 2015-10-23 11 21 27](https://cloud.githubusercontent.com/assets/3853/10701445/669f5cc4-7978-11e5-8bee-898f7e01ca09.png)

**Comment by pdpinch** [comment]
Sorry @justinabrahms the term "dashboard" is overloaded. 

The narrow fix here is to add a "CCX Coach" tab to the CCX view so that coaches can navigate from their CCX to the relevant coach dashboard. Currently the "CCX Coach" tab is only displayed on the master course.

**Comment by amir-qayyum-khan** [comment]
@pdpinch 
When user creates ccx then if inside ```create_ccx``` method i assign user a role == ccx_coach then he can access his dashboard from ccx.

**Comment by pdpinch** [comment]
closed via https://github.com/edx/edx-platform/pull/10672
